Add BrightID Verified User Registry contract
clrfund/monorepo pull request #157
Opened 2020-10-19 05:52 UTC by siftal

This is a contract to register verified users context ids by BrightID node's verification data, and be able to query a user verification

2020-10-19 10:22 UTC, xuhcc requested changes

2020-10-19 10:22 UTC, xuhcc commented on contracts/contracts/verifiedUserRegistry/VerifiedUserRegistry.sol
> +pragma solidity ^0.6.0;
Currently we use solidity 0.5.17. Is it possible to compile this contract with this version?

2020-10-19 10:22 UTC, xuhcc commented on contracts/contracts/verifiedUserRegistry/VerifiedUserRegistry.sol
> +}
Please fix linter errors: `yarn lint:contracts`

2020-10-20 19:32 UTC, adamstallard commented
@siftal Could you please add this event
```
event Sponsor(address);
```
and this function
```
 // sponsor any address provided as a parameter.
 function sponsor(address add) public {
   emit Sponsor(add);
 }
```
? That way we can also close this issue at the same time https://github.com/clrfund/monorepo/issues/136

2020-10-22 07:13 UTC, siftal commented on contracts/contracts/verifiedUserRegistry/VerifiedUserRegistry.sol
> +import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/Ownable.sol";
It's done.
https://github.com/siftal/monorepo/commit/faab2c83b3435b627f01809f1d65dcfda35b9c51

2020-10-22 07:15 UTC, siftal commented on contracts/contracts/verifiedUserRegistry/VerifiedUserRegistry.sol
> +pragma solidity ^0.6.0;
Yes. I updated the compiler version.
https://github.com/siftal/monorepo/commit/7493a5cb6b1c4677abfff620c14a7ec8a82ae38f

2020-10-22 07:21 UTC, siftal commented on contracts/contracts/verifiedUserRegistry/VerifiedUserRegistry.sol
> +}
I used these libraries to check my contracts, but they didn't find any error
https://github.com/protofire/solhint
https://github.com/duaraghav8/Ethlint
What linter do you use?

2020-10-22 11:56 UTC, xuhcc commented on contracts/contracts/verifiedUserRegistry/VerifiedUserRegistry.sol
> +}
`yarn lint:contracts` calls solhint with this config: https://github.com/clrfund/monorepo/blob/develop/contracts/.solhint.json

We use single quotes in our codebase: `error  Use single quotes for string literals  quotes`

2020-10-22 11:59 UTC, xuhcc approved these changes
Thanks @siftal !

2020-10-30 21:45 UTC, merged