add about details
clrfund/monorepo pull request #160
Opened 2020-10-21 20:24 UTC by auryn-macmillan

Added some about details and a link to the blog and forum.

2020-10-21 20:57 UTC, xuhcc requested changes
I think this page should be styled similarly to project page. I can do that if you want

2020-10-21 20:57 UTC, xuhcc commented on vue-app/src/App.vue
> +  color: $highlight-color;
Please don't change the base stylesheet.

2020-10-21 20:57 UTC, xuhcc commented on vue-app/src/views/About.vue
> +    <h2 class="content-heading">Why does clr.fund exist?</h2>
`.content-heading` is the class for top-level heading inside `#content` block. It should not apply to other elements. It is also redundant.

2020-10-22 17:16 UTC, auryn-macmillan commented on vue-app/src/views/About.vue
> +    <h2 class="content-heading">Why does clr.fund exist?</h2>
> I think this page should be styled similarly to project page. I can do that if you want

Yeah, that would be great!

2020-10-22 20:00 UTC, merged