OZ Proxy for MACI Factory with test coverage
clrfund/monorepo pull request #385
Opened 2021-09-21 07:21 UTC by viraj124

https://github.com/clrfund/monorepo/issues/359

2021-10-04 18:47 UTC, auryn-macmillan approved these changes
LGTM -- @daodesigner any issues with merging this?

2021-10-04 19:01 UTC, daodesigner commented
Yeah apologies or the delay here, only recently had time to do a serious review. @viraj124 please add constructors to initialize the singletons (also do this for the initial proxy contract I wrote please) and write tests to verify this.

2021-10-06 14:47 UTC, viraj124 commented
> Yeah apologies for the delay here, only recently had time to do a serious review. @viraj124 please add constructors to initialize the singletons (also do this for the initial proxy contract I wrote please) and write tests to verify this.

@daodesigner  I think they are already there https://github.com/viraj124/monorepo/blob/subgraph/contracts/contracts/ClrFundMACIFactoryDeployer.sol#L34 probably the test cases are missing I will check that

2021-10-06 15:33 UTC, daodesigner commented
hey just closing the loop here: I mean a constructor on the singleton(s) (template that gets passed in initially to the proxy factory)

2021-10-06 16:10 UTC, auryn-macmillan commented on contracts/contracts/ClrFundMACIFactory.sol
> +  function init(
For the avoidance of doubt, @viraj124, @daodesigner is suggesting (as I suggested in our DMs a while back) that this contract should have a constructor that calls your `init()` function.
This way you can:
1. choose how you want to deploy the contract, directly or via proxy.
2. deploy and immediately initialize the singleton.

2021-10-06 17:27 UTC, viraj124 commented on contracts/contracts/ClrFundMACIFactory.sol
> +  function init(
yeah got that @auryn-macmillan just updating the test cases

2021-10-06 18:04 UTC, viraj124 commented
@daodesigner pushed the changes

2021-10-08 15:46 UTC, auryn-macmillan requested changes

2021-10-08 15:46 UTC, auryn-macmillan commented on contracts/contracts/ClrFund.sol
> +    require(address(_maciFactory) != address(0), "ClrFund: invalid address");
I think these checks are unnecessary.
It's unlikely that anyone passes `address(0)` in as an argument, and if they do they only bork their own deployment, it doesn't do any damage to anyone else.

2021-10-08 15:46 UTC, auryn-macmillan commented on contracts/contracts/ClrFund.sol
> +  constructor(MACIFactory _maciFactory) public {
Given that the contracts are now ownable, the constructor should allow you to pass in `owner` as a parameter, rather than assuming msg.sender is the owner.

2021-10-08 15:47 UTC, viraj124 commented on contracts/contracts/ClrFund.sol
> +    require(address(_maciFactory) != address(0), "ClrFund: invalid address");
Just added to be very safe will remove 
Thanks

2021-10-08 15:48 UTC, viraj124 commented on contracts/contracts/ClrFund.sol
> +  constructor(MACIFactory _maciFactory) public {
Sure, 
Thanks

2021-10-12 20:53 UTC, auryn-macmillan approved these changes
LGTM. @daodesigner, this all check out?

2021-10-14 08:04 UTC, merged