clrfund/monorepo <- ethereum/clrfund
clrfund/monorepo pull request #388
Opened 2021-10-18 11:07 UTC by wackerow

Merging the `ethereum/clrfund` fork back into `clrfund/monorepo`. 

**Edit - @samajammin adding summary of changes:**

## Summary of changes 

- Product landing page: https://eth2clrfund.netlify.app/#/
- Educational content (10 about pages), customized based off network: https://eth2clrfund.netlify.app/#/about
- User onboarding flows
    - Dedicated landing pages for recipient (https://eth2clrfund.netlify.app/#/join) and contributor (https://eth2clrfund.netlify.app/#/verify) onboarding
    - Recipient application flow for the optimistic registry with expanded project data
        - Optional email input with form integration to Google Sheets (based on ENV variable)
    - BrightID flow for contributors with BrightID API integration
- Enhanced UX for full round lifecycle & user states
    - Store getters for computed properties across the app
    - Added relevant CTAs across the app depending on round & user state
    - Added a "join phase" for if no funding round exists
    - Countdown banners & contextual information depending on current phase
- Enhanced wallet integrations
    - Web3 plugin, with WalletConnect & MetaMask support
    - Prompts to switch networks
    - Auto prompt sign on refresh
- Cart features
    - Collapse / expand
    - Split evenly
    - Reallocation messages
- User profile view
    - Display ETH & token balance
- Enhanced project page view, based off new fields in recipient application
- Transaction success screens (for registry, contribution & reallocation txs)
- Subgraph integration
    - Replaced queryFilter for event logs
- Additional network & token support
    - Arbitrum support
    - Flexible content & UI depending on network & token used
- Mobile support across the app

2021-10-19 17:32 UTC, samajammin commented
@daodesigner note: we recognize this is a monster PR 😅. I'm planning to add some details on the primary changes here. Will do this ASAP - planning to do it this week - but in Lisbon for a conference & things are a bit hectic.

2021-10-26 13:29 UTC, samajammin commented
Ok @daodesigner - wasn't quite sure what level of detail to go into here but figured no sense in giving you the line-by-line or even the file-by-file changes. I've added this summary below but please let me know if you have more questions or would like to see more detail. I've also included preview deploy links where relevant.

# Summary of changes 

- Product landing page: https://eth2clrfund.netlify.app/#/
- Educational content (10 about pages), customized based off network: https://eth2clrfund.netlify.app/#/about
- User onboarding flows
    - Dedicated landing pages for recipient (https://eth2clrfund.netlify.app/#/join) and contributor (https://eth2clrfund.netlify.app/#/verify) onboarding
    - Recipient application flow for the optimistic registry with expanded project data
        - Optional email input with form integration to Google Sheets (based on ENV variable)
    - BrightID flow for contributors with BrightID API integration
- Enhanced UX for full round lifecycle & user states
    - Store getters for computed properties across the app
    - Added relevant CTAs across the app depending on round & user state
    - Added a "join phase" for if no funding round exists
    - Countdown banners & contextual information depending on current phase
- Enhanced wallet integrations
    - Web3 plugin, with WalletConnect & MetaMask support
    - Prompts to switch networks
    - Auto prompt sign on refresh
- Cart features
    - Collapse / expand
    - Split evenly
    - Reallocation messages
- User profile view
    - Display ETH & token balance
- Enhanced project page view, based off new fields in recipient application
- Transaction success screens (for registry, contribution & reallocation txs)
- Subgraph integration
    - Replaced queryFilter for event logs
- Additional network & token support
    - Arbitrum support
    - Flexible content & UI depending on network & token used
- Mobile support across the app

2021-10-26 16:48 UTC, samajammin commented
@auryn-macmillan @daodesigner regarding the support for viewing multiple rounds (see discussion in https://github.com/ethereum/clrfund/issues/431) - @pettinarip is currently working on an implementation to add the funding round factory & funding round to the route params which should be a more robust solution than the current approach of deploying multiple instances of the application & referencing the different IPFS hashes. We'll keep you focused on that but in short, we believe we should keep that work separate from this merge PR given that it alone may add some complex changes. The application as-is keeps parity with the existing monorepo codebase.

2021-10-27 14:18 UTC, daodesigner requested changes
Add Information to Docs regarding Google spread sheet tracking (very cool feature) and BrightID Context for Arbitrum if possible. Otherwise looks good, great work everyone!

2021-10-27 14:18 UTC, daodesigner commented on vue-app/.env.example
> +GOOGLE_APPLICATION_CREDENTIALS=
Add to documentation how to get the Spreadsheet parameters

2021-10-27 14:18 UTC, daodesigner commented on vue-app/.env.example
> +VUE_APP_GOOGLE_SPREADSHEET_ID=
What does this track?

2021-10-27 14:18 UTC, daodesigner commented on vue-app/.env.example
> +VUE_APP_BRIGHTID_CONTEXT=clr.fund
Is there a context on Arbitrum that we can use set up already?

2021-10-27 14:54 UTC, samajammin commented on vue-app/.env.example
> +VUE_APP_BRIGHTID_CONTEXT=clr.fund
The BrightID context is distinct from the Ethereum chain we use - it's specific to BrightID. I'll add some documentation around this.

2021-10-28 00:42 UTC, samajammin commented
@daodesigner I've expanded the docs to address your change requests. You can see the specific changes here: https://github.com/ethereum/clrfund/pull/453

The Google Sheet integration is definitely a bit of an edge use case given the use of Netlify functions, so no hard feelings if you'd rather just rip out that feature entirely. It's disabled by default though so shouldn't cause any harm to leave in (other than more code/files).

Please let me know if you have any other questions or requests!

2021-10-28 03:35 UTC, daodesigner approved these changes

2021-10-28 03:35 UTC, merged

2021-10-28 15:21 UTC, auryn-macmillan commented
![its happening](https://media2.giphy.com/media/5mBE2MiMVFITS/giphy.gif?cid=ecf05e477bn4xpxyd3moxun699z62jd994tjd6vqkdlzzpz0&rid=giphy.gif)

2021-10-28 16:09 UTC, corwintines commented
Oh baby!