Implement light theme
clrfund/monorepo pull request #410
Opened 2021-12-02 03:09 UTC by yuetloo

2021-12-16 19:39 UTC, daodesigner commented
Closes #405, closes #395 , closes #393  , closes #399 , closes #398 
@yuetloo please provide an estimate of time spent so far for sprint burndown. Keep up the great work!

2021-12-16 20:30 UTC, yuetloo commented
@daodesigner, I spent 15 hours on this PR so far.

2022-01-11 20:07 UTC, daodesigner requested changes

2022-01-11 20:07 UTC, daodesigner commented on README.md
> +/
```
/
├─── /projects
│     └── /:id
├─── /round-information
├─── /rounds
│     └── /:address
├─── /about
│      ├──/maci
│      ├──/sybil-resistance
│      ├──/layer-2
│      ├──/how-it-works
│      │   ├──/contributors
│      │   └──/recipients
│      ├──/public-goods
│      ├──/quadratic-funding
│      └──/decentralization
├─── /recipients
├─── /verify
│      ├──/success/:hash?
│      └──/connect
├─── /join
│      ├──/success/:hash
│      ├──/project
│      ├──/fund
│      ├──/team
│      ├──/links
│      ├──/image
│      ├──/furthestStep
│      └──/summary
├─── /cart
└─── /transaction-success
       ├──/reallocation/:hash?
       └──/contribution/:hash?
```

2022-01-11 20:07 UTC, daodesigner commented on vue-app/src/views/Verify.vue
> -.loader {
where did these definitions move to?

2022-01-11 20:41 UTC, yuetloo commented on vue-app/src/views/Verify.vue
> -.loader {
they were defined in Loader.vue, exactly the same, so, I removed it here.

2022-05-10 18:11 UTC, merged